quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_IP}:${DB_PORT}/${DB_NAME}
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.schema-management.create-schemas=true

# RabbitMQ
rabbitmq-host=192.168.1.154
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

quarkus.rabbitmq.devservices.enabled=false

mp.messaging.incoming.accounts.connector=smallrye-rabbitmq
mp.messaging.incoming.accounts.exchange.name=accounts
mp.messaging.incoming.accounts.queue.name=accounts-queue
mp.messaging.incoming.accounts.routing-key=#
mp.messaging.incoming.accounts.content-type=application/json